from __future__ import annotations

import base64
import hashlib
from datetime import datetime, timedelta, timezone
from typing import Any

import bcrypt
from bson import ObjectId
from bson.errors import InvalidId
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from pymongo.errors import DuplicateKeyError

from backend.core.config import get_settings
from backend.db.mongo import get_users_collection


PASSWORD_HASH_PREFIX = "bcrypt_sha256$"
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login")


def _is_valid_email(email: str) -> bool:
    local, sep, domain = email.partition("@")
    return bool(sep and local and domain and "." in domain)


def _normalize_email(email: str) -> str:
    return email.strip().lower()


def _serialize_user(user_doc: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": str(user_doc["_id"]),
        "email": user_doc["email"],
        "created_at": user_doc.get("created_at"),
    }


def _to_password_bytes(password: str) -> bytes:
    return password.encode("utf-8")


def _prehash_password(password: str) -> bytes:
    digest = hashlib.sha256(_to_password_bytes(password)).digest()
    return base64.b64encode(digest)


def hash_password(password: str) -> str:
    hashed = bcrypt.hashpw(_prehash_password(password), bcrypt.gensalt())
    return f"{PASSWORD_HASH_PREFIX}{hashed.decode('utf-8')}"


def verify_password(plain_password: str, hashed_password: str) -> bool:
    hashed_password_bytes = hashed_password.encode("utf-8")

    try:
        if hashed_password.startswith(PASSWORD_HASH_PREFIX):
            prefixed_hash = hashed_password[len(PASSWORD_HASH_PREFIX) :].encode("utf-8")
            return bcrypt.checkpw(_prehash_password(plain_password), prefixed_hash)

        # Backward compatibility for existing bcrypt hashes stored without the prefix.
        return bcrypt.checkpw(_to_password_bytes(plain_password), hashed_password_bytes)
    except ValueError:
        # bcrypt>=5 raises ValueError for inputs over 72 bytes. Older hashes may have
        # been generated by backends that truncated long inputs silently, so retry with
        # a manual truncation for legacy hash verification only.
        password_bytes = _to_password_bytes(plain_password)
        if hashed_password.startswith(PASSWORD_HASH_PREFIX) or len(password_bytes) <= 72:
            return False
        try:
            return bcrypt.checkpw(password_bytes[:72], hashed_password_bytes)
        except ValueError:
            return False
    except TypeError:
        return False


def create_access_token(subject: str, email: str) -> str:
    settings = get_settings()
    now = datetime.now(timezone.utc)
    expire = now + timedelta(minutes=settings.JWT_EXPIRE_MINUTES)
    payload = {
        "sub": subject,
        "email": email,
        "iat": int(now.timestamp()),
        "exp": int(expire.timestamp()),
    }
    return jwt.encode(payload, settings.JWT_SECRET, algorithm=settings.JWT_ALGORITHM)


def create_user(email: str, password: str) -> dict[str, Any]:
    normalized = _normalize_email(email)
    if not _is_valid_email(normalized):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid email format")

    doc = {
        "email": normalized,
        "password_hash": hash_password(password),
        "created_at": datetime.now(timezone.utc),
    }
    try:
        inserted = get_users_collection().insert_one(doc)
    except DuplicateKeyError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="User already exists") from exc

    doc["_id"] = inserted.inserted_id
    return _serialize_user(doc)


def authenticate_user(email: str, password: str) -> dict[str, Any] | None:
    normalized = _normalize_email(email)
    user = get_users_collection().find_one({"email": normalized})
    if not user:
        return None
    if not verify_password(password, user["password_hash"]):
        return None
    return _serialize_user(user)


def _credentials_exception() -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Unauthorized",
        headers={"WWW-Authenticate": "Bearer"},
    )


async def get_current_user(token: str = Depends(oauth2_scheme)) -> dict[str, Any]:
    settings = get_settings()
    try:
        payload = jwt.decode(token, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])
        subject = payload.get("sub")
        if not subject:
            raise _credentials_exception()
        user_doc = get_users_collection().find_one({"_id": ObjectId(subject)})
        if not user_doc:
            raise _credentials_exception()
        return user_doc
    except (JWTError, InvalidId) as exc:
        raise _credentials_exception() from exc
